# fly.toml for persistent Langflow deployment

app = "langflow-no-nginx"
primary_region = "syd"

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = "disabled"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2

[mounts]
  source = "langflow_data"
  destination = "/code"
