# fly.toml app configuration file generated for langflow-no-nginx-273xcq on 2025-05-20T18:18:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langflow-no-nginx-273xcq'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
